# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Auto-assigned unique number within exam paper')),
                ('question_text', models.TextField(help_text='Plain text ONLY with [[EQ:N]] placeholders, no HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_questions', to='editor.exampaper')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='One of: A, B, C, D', max_length=1)),
                ('option_text', models.TextField(help_text='Plain text ONLY with [[EQ:N]] placeholders, no HTML')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='editor.question')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='QuestionEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex', models.TextField(help_text='Raw LaTeX only, e.g. A = A_0(1 + \\sin t)')),
                ('placeholder', models.CharField(help_text='Placeholder in text, e.g. [[EQ:1]]', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of appearance in question text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equations', to='editor.question')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greek', 'Greek Letters'), ('math-ops', 'Math Operators'), ('fractions', 'Fractions & Roots'), ('powers', 'Powers & Indices'), ('calculus', 'Calculus'), ('vectors', 'Vectors & Matrices'), ('trig', 'Trigonometry'), ('phys', 'Physics Symbols'), ('chem', 'Chemical Formulas'), ('chem-reac', 'Chemical Reactions'), ('units', 'Units'), ('sets', 'Sets & Logic'), ('misc', 'Miscellaneous')], max_length=20)),
                ('exam_type', models.CharField(choices=[('neet', 'NEET'), ('kcet', 'KCET/CET'), ('jee', 'JEE'), ('all', 'All')], default='all', max_length=10)),
                ('latex', models.TextField(help_text='LaTeX source')),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('search_tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'display_name'],
                'indexes': [models.Index(fields=['category'], name='editor_symb_categor_7ccca5_idx'), models.Index(fields=['exam_type'], name='editor_symb_exam_ty_cb5258_idx'), models.Index(fields=['is_favorite'], name='editor_symb_is_favo_3df9ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptionEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex', models.TextField(help_text='Raw LaTeX only')),
                ('placeholder', models.CharField(help_text='Placeholder in text, e.g. [[EQ:1]]', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of appearance in option text')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equations', to='editor.option')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['option', 'position'], name='editor_opti_option__f00120_idx')],
                'unique_together': {('option', 'placeholder')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_paper', 'question_number'], name='editor_ques_exam_pa_237590_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam_paper', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'label'], name='editor_opti_questio_0f8c2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'label')},
        ),
        migrations.AddIndex(
            model_name='questionequation',
            index=models.Index(fields=['question', 'position'], name='editor_ques_questio_21a90c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionequation',
            unique_together={('question', 'placeholder')},
        ),
    ]
