# Generated by Django 5.2.17 on 2026-08-26 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_question_option_questionequation_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='linked_page',
            field=models.OneToOneField(blank=True, help_text='The free-form page that syncs with this question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_question', to='editor.exampage'),
        ),
    ]
