# Generated by Django 5.2.17 on 2026-08-27 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_question_linked_page'),
        ('questionbank', '0006_question_question_bank_non_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExamPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('marks_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('negative_marks_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='editor.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_placements', to='questionbank.question')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['exam_paper', 'sequence'], name='editor_exam_exam_pa_3b8c67_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam_paper', 'question'), name='unique_question_per_paper'), models.UniqueConstraint(fields=('exam_paper', 'sequence'), name='unique_sequence_per_paper')],
            },
        ),
    ]
