# Generated by Django 5.2.17 on 2026-08-27 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_alter_question_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncontent',
            name='latex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questioncontent',
            name='latex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solutioncontent',
            name='latex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optioncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('EQUATION', 'Equation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('EQUATION', 'Equation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solutioncontent',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('EQUATION', 'Equation')], max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionbank.questionbank'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank'], name='questionban_questio_1a3793_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['owner'], name='questionban_owner_i_d2de68_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_bank_name_per_owner'),
        ),
    ]
